// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XitiqueAPI.Data;

#nullable disable

namespace XitiqueAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XitiqueAPI.Models.Client", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("DailyAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAvailable")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("XitiqueAPI.Models.DailyDeposit", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("DailyAccumulated")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DailyDeposits");
                });

            modelBuilder.Entity("XitiqueAPI.Models.Loan", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DevolutionData")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("XitiqueAPI.Models.TotalAllClientsBalance", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("TotalAvailable")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TotalAllClientsBalance");
                });

            modelBuilder.Entity("XitiqueAPI.Models.TotalDailyDeposits", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TotalDailyDeposits");
                });

            modelBuilder.Entity("XitiqueAPI.Models.Transaction", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("ClientAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
